import pytest
import src.scrape as sc
import src.load_data as ld
from src import clean
from bs4 import BeautifulSoup

@pytest.mark.db
def test_load_data():
    try:
        sc.load_data("./src/llm_generated_applicant_data.json")
    except FileNotFoundError:
        pytest.fail('Failed to load JSON file')

@pytest.mark.db
def test_scrape_data(mock_web_return, monkeypatch):
    def mock_fetch(page):
        return mock_web_return, 200

    # Using last id in the list to test cutting the parse short when lastID is found
    monkeypatch.setattr("src.scrape._fetch_page", mock_fetch)
    data = sc.scrape_data(1020269)
    assert len(data) == 19

    data = sc.scrape_data(1020288)
    assert len(data) == 0

    #Check for bad fetch
    def mock_bad_404_fetch(page):
        return None, 404
    monkeypatch.setattr("src.scrape._fetch_page", mock_bad_404_fetch)
    data = sc.scrape_data(1)
    assert data == None

@pytest.mark.db
def test_fetchPage(monkeypatch):
    class mock_response:
        def __init__(self, message, status_code):
            self.data = message
            self.status = status_code

    def return_200(type, url, what):
        return mock_response("Test", 200)
    def return_400(type, url, what):
        return mock_response("Test", 400)
    def return_404(type, url, what):
        return mock_response("Test", 404)
    def return_500(type, url, what):
        return mock_response("Test", 500)

    monkeypatch.setattr("urllib3.PoolManager.request", return_200)
    data, status = sc._fetch_page(1)
    assert status == 200

    monkeypatch.setattr("urllib3.PoolManager.request", return_400)
    data, status = sc._fetch_page(1)
    assert status == 400

    monkeypatch.setattr("urllib3.PoolManager.request", return_404)
    data, status = sc._fetch_page(1)
    assert status == 404

    monkeypatch.setattr("urllib3.PoolManager.request", return_500)
    data, status = sc._fetch_page(1)
    assert status == 500

@pytest.mark.db
def test_insert_entries(pg_connection,monkeypatch):
    def test_server(**conf):
        return pg_connection
    monkeypatch.setattr("psycopg.connect", test_server)
    ld.insert_entries(parse_return)

@pytest.mark.db
def test_clean_data(mock_web_return):
    # Couldn't get this test case through the scrape tests with the data on hand
    parsedPage = BeautifulSoup(mock_web_return, "html.parser")
    tableRows = parsedPage.find_all("tr")
    data = clean.clean_data(tableRows, 1)
    assert len(data) == 20

# Pulled data in reverse, so there should be no entry with 1
mock_single_entry = [
    {
        "id": 1,
        "program": "Environmental Economics",
        "university": "Stockholm University",
        "comments": "None",
        "date_added": "May 31, 2026",
        "url": "https://www.thegradcafe.com/result/1020288",
        "status": "Accepted",
        "status_date": "May 31",
        "accepted": "None",
        "rejected": "None",
        "term": "Fall 2026",
        "US/International": "International",
        "degree": "PhD",
        "gpa": "None",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "Environmental Economics",
        "llm-generated-university": "Stockholm University"
    }
    ]

parse_return = [
    {
        "id": 1020288,
        "program": "Environmental Economics",
        "university": "Stockholm University",
        "comments": "None",
        "date_added": "May 31, 2026",
        "url": "https://www.thegradcafe.com/result/1020288",
        "status": "Accepted",
        "status_date": "May 31",
        "accepted": "None",
        "rejected": "None",
        "term": "Fall 2026",
        "US/International": "International",
        "degree": "PhD",
        "gpa": "None",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "None",
        "llm-generated-university": "None",
    },
    {
        "id": 1020287,
        "program": "Global Health",
        "university": "Meharry Medical College",
        "comments": "None",
        "date_added": "May 30, 2026",
        "url": "https://www.thegradcafe.com/result/1020287",
        "status": "Accepted",
        "status_date": "May 29",
        "accepted": "None",
        "rejected": "None",
        "term": "Fall 2026",
        "US/International": "American",
        "degree": "PhD",
        "gpa": "3.90",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "None",
        "llm-generated-university": "None",
    },
    {
        "id": 1020286,
        "program": "Public Policy",
        "university": "University of Massachusetts",
        "comments": "None",
        "date_added": "May 29, 2026",
        "url": "https://www.thegradcafe.com/result/1020286",
        "status": "Wait listed",
        "status_date": "May 29",
        "accepted": "None",
        "rejected": "None",
        "term": "Fall 2026",
        "US/International": "International",
        "degree": "PhD",
        "gpa": "None",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "None",
        "llm-generated-university": "None",
    },
    {
        "id": 1020285,
        "program": "Engineering Science",
        "university": "University of Oxford",
        "comments":
            "Applying as a (home student) Oxford undergrad. Didn't receive the offer until super \
            late...!",
        "date_added": "May 29, 2026",
        "url": "https://www.thegradcafe.com/result/1020285",
        "status": "Accepted",
        "status_date": "Apr 17",
        "accepted": "None",
        "rejected": "None",
        "term": "Fall 2026",
        "US/International": "Other",
        "degree": "PhD",
        "gpa": "None",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "None",
        "llm-generated-university": "None",
    },
    {
        "id": 1020284,
        "program": "Mechanical Engineering",
        "university": "Rice University",
        "comments": "Duke Master of Science in ME, GPA: 3.85",
        "date_added": "May 29, 2026",
        "url": "https://www.thegradcafe.com/result/1020284",
        "status": "Accepted",
        "status_date": "May 08",
        "accepted": "None",
        "rejected": "None",
        "term": "Fall 2026",
        "US/International": "International",
        "degree": "PhD",
        "gpa": "3.84",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "None",
        "llm-generated-university": "None",
    },
    {
        "id": 1020283,
        "program": "Computer Science",
        "university": "Georgia Institute of Technology",
        "comments": "None",
        "date_added": "May 29, 2026",
        "url": "https://www.thegradcafe.com/result/1020283",
        "status": "Rejected",
        "status_date": "May 29",
        "accepted": "None",
        "rejected": "May 29",
        "term": "Fall 2026",
        "US/International": "American",
        "degree": "PhD",
        "gpa": "3.90",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "None",
        "llm-generated-university": "None",
    },
    {
        "id": 1020282,
        "program": "Computer Science And Engineering",
        "university": "University of Delaware",
        "comments": "None",
        "date_added": "May 29, 2026",
        "url": "https://www.thegradcafe.com/result/1020282",
        "status": "Wait listed",
        "status_date": "May 29",
        "accepted": "None",
        "rejected": "None",
        "term": "Fall 2026",
        "US/International": "International",
        "degree": "PhD",
        "gpa": "3.50",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "None",
        "llm-generated-university": "None",
    },
    {
        "id": 1020281,
        "program": "Neuroscience",
        "university": "McGill University",
        "comments": "None",
        "date_added": "May 29, 2026",
        "url": "https://www.thegradcafe.com/result/1020281",
        "status": "Accepted",
        "status_date": "May 25",
        "accepted": "None",
        "rejected": "None",
        "term": "Fall 2026",
        "US/International": "International",
        "degree": "Masters",
        "gpa": "None",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "None",
        "llm-generated-university": "None",
    },
    {
        "id": 1020280,
        "program": "Consumer Science",
        "university": "Ohio State University",
        "comments":
            "I was really surprised! The email was sent at 10 p.m. local time. To be honest, as \
            an international student, I had already given up hope haha.",
        "date_added": "May 29, 2026",
        "url": "https://www.thegradcafe.com/result/1020280",
        "status": "Accepted",
        "status_date": "May 15",
        "accepted": "None",
        "rejected": "None",
        "term": "Fall 2026",
        "US/International": "International",
        "degree": "Masters",
        "gpa": "3.84",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "None",
        "llm-generated-university": "None",
    },
    {
        "id": 1020279,
        "program": "Economics",
        "university": "Queen's University",
        "comments":
            "Advanced Macro: A+ Advanced Micro: A Econometrics: B+ Cal 1, 2, and Linear Alg. Got \
            ghosted without any response.",
        "date_added": "May 28, 2026",
        "url": "https://www.thegradcafe.com/result/1020279",
        "status": "Rejected",
        "status_date": "May 28",
        "accepted": "None",
        "rejected": "May 28",
        "term": "Fall 2026",
        "US/International": "Other",
        "degree": "Masters",
        "gpa": "3.50",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "None",
        "llm-generated-university": "None",
    },
    {
        "id": 1020278,
        "program": "Economics",
        "university": "New York University",
        "comments": "Ridiculously late",
        "date_added": "May 28, 2026",
        "url": "https://www.thegradcafe.com/result/1020278",
        "status": "Rejected",
        "status_date": "May 28",
        "accepted": "None",
        "rejected": "May 28",
        "term": "Fall 2026",
        "US/International": "International",
        "degree": "PhD",
        "gpa": "3.78",
        "gre": "159",
        "grev": "170",
        "greaw": "3.50",
        "llm-generated-program": "None",
        "llm-generated-university": "None",
    },
    {
        "id": 1020277,
        "program": "Materials Science",
        "university": "Colorado School of Mines",
        "comments": "Rejected for Master's Thesis, bumped down to Non-Thesis",
        "date_added": "May 28, 2026",
        "url": "https://www.thegradcafe.com/result/1020277",
        "status": "Accepted",
        "status_date": "May 28",
        "accepted": "None",
        "rejected": "None",
        "term": "Fall 2026",
        "US/International": "American",
        "degree": "Masters",
        "gpa": "3.40",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "None",
        "llm-generated-university": "None",
    },
    {
        "id": 1020276,
        "program": "Statistics",
        "university": "Columbia University",
        "comments": "None",
        "date_added": "May 28, 2026",
        "url": "https://www.thegradcafe.com/result/1020276",
        "status": "Accepted",
        "status_date": "Feb 27",
        "accepted": "None",
        "rejected": "None",
        "term": "Fall 2026",
        "US/International": "International",
        "degree": "PhD",
        "gpa": "None",
        "gre": "168",
        "grev": "164",
        "greaw": "4.00",
        "llm-generated-program": "None",
        "llm-generated-university": "None",
    },
    {
        "id": 1020275,
        "program": "Philosophy",
        "university": "Wayne State University",
        "comments": "Grad GPA. Better late than never. 4a/15r/0p",
        "date_added": "May 27, 2026",
        "url": "https://www.thegradcafe.com/result/1020275",
        "status": "Rejected",
        "status_date": "May 27",
        "accepted": "None",
        "rejected": "May 27",
        "term": "Fall 2026",
        "US/International": "American",
        "degree": "PhD",
        "gpa": "4.00",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "None",
        "llm-generated-university": "None",
    },
    {
        "id": 1020274,
        "program": "Physics",
        "university": "William & Mary",
        "comments":
            "HEP-ex BSc was top British uni, 55% (2:2) MSc was mid British uni, 71% (distinction) \
            Only relevant experience is BSc and MSc project. No publications, talks, etc. Not \
            sure how strong my LORs are. Email to check portal",
        "date_added": "May 27, 2026",
        "url": "https://www.thegradcafe.com/result/1020274",
        "status": "Rejected",
        "status_date": "May 27",
        "accepted": "None",
        "rejected": "May 27",
        "term": "Fall 2026",
        "US/International": "American",
        "degree": "PhD",
        "gpa": "None",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "None",
        "llm-generated-university": "None",
    },
    {
        "id": 1020273,
        "program": "Computer Science",
        "university": "University of California",
        "comments":
            "For the MSCS (Scientists and Engineers track, for non cs majors). Kinda surprised \
            since I have a philosophy BA and pretty minimal ECs and anything relevant really. My \
            Letters were good tho, I know that. Also my SoP made some pretty sophisticated links \
            to modern machine learning, not just the surface level \"ethics... blah blah\". \
            Seems like the cohort is massive, but considering my background I am content.",
        "date_added": "May 27, 2026",
        "url": "https://www.thegradcafe.com/result/1020273",
        "status": "Accepted",
        "status_date": "May 27",
        "accepted": "None",
        "rejected": "None",
        "term": "Fall 2026",
        "US/International": "American",
        "degree": "Masters",
        "gpa": "None",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "None",
        "llm-generated-university": "None",
    },
    {
        "id": 1020272,
        "program": "Applied Statistics",
        "university": "Cornell University",
        "comments":
            "Tier 2 Indian University. Applied on January 5th, interviewed on January 27. \
            Rejected on May 26. If you’re waiting till June, it’s rejection, good \
            luck.",
        "date_added": "May 26, 2026",
        "url": "https://www.thegradcafe.com/result/1020272",
        "status": "Rejected",
        "status_date": "May 26",
        "accepted": "None",
        "rejected": "May 26",
        "term": "Fall 2026",
        "US/International": "International",
        "degree": "Masters",
        "gpa": "3.45",
        "gre": "170",
        "grev": "157",
        "greaw": "4.00",
        "llm-generated-program": "None",
        "llm-generated-university": "None",
    },
    {
        "id": 1020271,
        "program": "Computer Science",
        "university": "Washington State University",
        "comments":
            "First interviews and said he will hire for Sping 2026. Then ghosted. And then \
            rejected over email stating no bandwidth.",
        "date_added": "May 26, 2026",
        "url": "https://www.thegradcafe.com/result/1020271",
        "status": "Interview",
        "status_date": "May 22",
        "accepted": "None",
        "rejected": "None",
        "term": "Fall 2026",
        "US/International": "International",
        "degree": "PhD",
        "gpa": "3.80",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "None",
        "llm-generated-university": "None",
    },
    {
        "id": 1020270,
        "program": "Computer Science",
        "university": "Michigan State University",
        "comments":
            "Applied for PhD but offered Masters. Asked for Integrated masters, but they refused.",
        "date_added": "May 26, 2026",
        "url": "https://www.thegradcafe.com/result/1020270",
        "status": "Accepted",
        "status_date": "May 26",
        "accepted": "None",
        "rejected": "None",
        "term": "Fall 2026",
        "US/International": "International",
        "degree": "PhD",
        "gpa": "3.80",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "None",
        "llm-generated-university": "None",
    },
    {
        "id": 1020269,
        "program": "Education",
        "university": "Wilfrid Laurier University",
        "comments": "None",
        "date_added": "May 26, 2026",
        "url": "https://www.thegradcafe.com/result/1020269",
        "status": "Accepted",
        "status_date": "May 22",
        "accepted": "None",
        "rejected": "None",
        "term": "Fall 2026",
        "US/International": "American",
        "degree": "Masters",
        "gpa": "None",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "None",
        "llm-generated-university": "None",
    },
]

llm_return = [
    {
        "id": 1020288,
        "program": "Environmental Economics",
        "university": "Stockholm University",
        "comments": "None",
        "date_added": "May 31, 2026",
        "url": "https://www.thegradcafe.com/result/1020288",
        "status": "Accepted",
        "status_date": "May 31",
        "accepted": "None",
        "rejected": "None",
        "term": "Fall 2026",
        "US/International": "International",
        "degree": "PhD",
        "gpa": "None",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "Environmental Economics",
        "llm-generated-university": "Stockholm University",
    },
    {
        "id": 1020287,
        "program": "Global Health",
        "university": "Meharry Medical College",
        "comments": "None",
        "date_added": "May 30, 2026",
        "url": "https://www.thegradcafe.com/result/1020287",
        "status": "Accepted",
        "status_date": "May 29",
        "accepted": "None",
        "rejected": "None",
        "term": "Fall 2026",
        "US/International": "American",
        "degree": "PhD",
        "gpa": "3.90",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "Global Health",
        "llm-generated-university": "Meharry Medical College",
    },
    {
        "id": 1020286,
        "program": "Public Policy",
        "university": "University of Massachusetts",
        "comments": "None",
        "date_added": "May 29, 2026",
        "url": "https://www.thegradcafe.com/result/1020286",
        "status": "Wait listed",
        "status_date": "May 29",
        "accepted": "None",
        "rejected": "None",
        "term": "Fall 2026",
        "US/International": "International",
        "degree": "PhD",
        "gpa": "None",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "Public Policy",
        "llm-generated-university": "University of Massachusetts Lowell",
    },
    {
        "id": 1020285,
        "program": "Engineering Science",
        "university": "University of Oxford",
        "comments":
            "Applying as a (home student) Oxford undergrad. Didn't receive the offer until super \
            late...!",
        "date_added": "May 29, 2026",
        "url": "https://www.thegradcafe.com/result/1020285",
        "status": "Accepted",
        "status_date": "Apr 17",
        "accepted": "None",
        "rejected": "None",
        "term": "Fall 2026",
        "US/International": "Other",
        "degree": "PhD",
        "gpa": "None",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "Engineering Science",
        "llm-generated-university": "University of Oxford",
    },
    {
        "id": 1020284,
        "program": "Mechanical Engineering",
        "university": "Rice University",
        "comments": "Duke Master of Science in ME, GPA: 3.85",
        "date_added": "May 29, 2026",
        "url": "https://www.thegradcafe.com/result/1020284",
        "status": "Accepted",
        "status_date": "May 08",
        "accepted": "None",
        "rejected": "None",
        "term": "Fall 2026",
        "US/International": "International",
        "degree": "PhD",
        "gpa": "3.84",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "Mechanical Engineering",
        "llm-generated-university": "Rice University",
    },
    {
        "id": 1020283,
        "program": "Computer Science",
        "university": "Georgia Institute of Technology",
        "comments": "None",
        "date_added": "May 29, 2026",
        "url": "https://www.thegradcafe.com/result/1020283",
        "status": "Rejected",
        "status_date": "May 29",
        "accepted": "None",
        "rejected": "May 29",
        "term": "Fall 2026",
        "US/International": "American",
        "degree": "PhD",
        "gpa": "3.90",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "Computer Science",
        "llm-generated-university": "Georgia Institute of Technology",
    },
    {
        "id": 1020282,
        "program": "Computer Science And Engineering",
        "university": "University of Delaware",
        "comments": "None",
        "date_added": "May 29, 2026",
        "url": "https://www.thegradcafe.com/result/1020282",
        "status": "Wait listed",
        "status_date": "May 29",
        "accepted": "None",
        "rejected": "None",
        "term": "Fall 2026",
        "US/International": "International",
        "degree": "PhD",
        "gpa": "3.50",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "Computational Science and Engineering",
        "llm-generated-university": "University of Delaware",
    },
    {
        "id": 1020281,
        "program": "Neuroscience",
        "university": "McGill University",
        "comments": "None",
        "date_added": "May 29, 2026",
        "url": "https://www.thegradcafe.com/result/1020281",
        "status": "Accepted",
        "status_date": "May 25",
        "accepted": "None",
        "rejected": "None",
        "term": "Fall 2026",
        "US/International": "International",
        "degree": "Masters",
        "gpa": "None",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "",
        "llm-generated-university": "McGill University",
    },
    {
        "id": 1020280,
        "program": "Consumer Science",
        "university": "Ohio State University",
        "comments":
            "I was really surprised! The email was sent at 10 p.m. local time. To be honest, as \
            an international student, I had already given up hope haha.",
        "date_added": "May 29, 2026",
        "url": "https://www.thegradcafe.com/result/1020280",
        "status": "Accepted",
        "status_date": "May 15",
        "accepted": "None",
        "rejected": "None",
        "term": "Fall 2026",
        "US/International": "International",
        "degree": "Masters",
        "gpa": "3.84",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "Consumer Science",
        "llm-generated-university": "Ohio State University",
    },
    {
        "id": 1020279,
        "program": "Economics",
        "university": "Queen's University",
        "comments":
            "Advanced Macro: A+ Advanced Micro: A Econometrics: B+ Cal 1, 2, and Linear Alg. Got \
            ghosted without any response.",
        "date_added": "May 28, 2026",
        "url": "https://www.thegradcafe.com/result/1020279",
        "status": "Rejected",
        "status_date": "May 28",
        "accepted": "None",
        "rejected": "May 28",
        "term": "Fall 2026",
        "US/International": "Other",
        "degree": "Masters",
        "gpa": "3.50",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "Economics",
        "llm-generated-university": "Queen’s University",
    },
    {
        "id": 1020278,
        "program": "Economics",
        "university": "New York University",
        "comments": "Ridiculously late",
        "date_added": "May 28, 2026",
        "url": "https://www.thegradcafe.com/result/1020278",
        "status": "Rejected",
        "status_date": "May 28",
        "accepted": "None",
        "rejected": "May 28",
        "term": "Fall 2026",
        "US/International": "International",
        "degree": "PhD",
        "gpa": "3.78",
        "gre": "159",
        "grev": "170",
        "greaw": "3.50",
        "llm-generated-program": "Economics",
        "llm-generated-university": "New York University",
    },
    {
        "id": 1020277,
        "program": "Materials Science",
        "university": "Colorado School of Mines",
        "comments": "Rejected for Master's Thesis, bumped down to Non-Thesis",
        "date_added": "May 28, 2026",
        "url": "https://www.thegradcafe.com/result/1020277",
        "status": "Accepted",
        "status_date": "May 28",
        "accepted": "None",
        "rejected": "None",
        "term": "Fall 2026",
        "US/International": "American",
        "degree": "Masters",
        "gpa": "3.40",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "Materials Science",
        "llm-generated-university": "Colorado School of Mines",
    },
    {
        "id": 1020276,
        "program": "Statistics",
        "university": "Columbia University",
        "comments": "None",
        "date_added": "May 28, 2026",
        "url": "https://www.thegradcafe.com/result/1020276",
        "status": "Accepted",
        "status_date": "Feb 27",
        "accepted": "None",
        "rejected": "None",
        "term": "Fall 2026",
        "US/International": "International",
        "degree": "PhD",
        "gpa": "None",
        "gre": "168",
        "grev": "164",
        "greaw": "4.00",
        "llm-generated-program": "Statistics",
        "llm-generated-university": "Columbia University",
    },
    {
        "id": 1020275,
        "program": "Philosophy",
        "university": "Wayne State University",
        "comments": "Grad GPA. Better late than never. 4a/15r/0p",
        "date_added": "May 27, 2026",
        "url": "https://www.thegradcafe.com/result/1020275",
        "status": "Rejected",
        "status_date": "May 27",
        "accepted": "None",
        "rejected": "May 27",
        "term": "Fall 2026",
        "US/International": "American",
        "degree": "PhD",
        "gpa": "4.00",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "Philosophy",
        "llm-generated-university": "Wayne State University",
    },
    {
        "id": 1020274,
        "program": "Physics",
        "university": "William & Mary",
        "comments":
            "HEP-ex BSc was top British uni, 55% (2:2) MSc was mid British uni, 71% (distinction) \
            Only relevant experience is BSc and MSc project. No publications, talks, etc. Not \
            sure how strong my LORs are. Email to check portal",
        "date_added": "May 27, 2026",
        "url": "https://www.thegradcafe.com/result/1020274",
        "status": "Rejected",
        "status_date": "May 27",
        "accepted": "None",
        "rejected": "May 27",
        "term": "Fall 2026",
        "US/International": "American",
        "degree": "PhD",
        "gpa": "None",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "Physics",
        "llm-generated-university": "William & Mary",
    },
    {
        "id": 1020273,
        "program": "Computer Science",
        "university": "University of California",
        "comments":
            "For the MSCS (Scientists and Engineers track, for non cs majors). Kinda surprised \
            since I have a philosophy BA and pretty minimal ECs and anything relevant really. My \
            Letters were good tho, I know that. Also my SoP made some pretty sophisticated links \
            to modern machine learning, not just the surface level \"ethics... blah blah\". \
            Seems like the cohort is massive, but considering my background I am content.",
        "date_added": "May 27, 2026",
        "url": "https://www.thegradcafe.com/result/1020273",
        "status": "Accepted",
        "status_date": "May 27",
        "accepted": "None",
        "rejected": "None",
        "term": "Fall 2026",
        "US/International": "American",
        "degree": "Masters",
        "gpa": "None",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "Computer Science",
        "llm-generated-university": "University of California, Davis",
    },
    {
        "id": 1020272,
        "program": "Applied Statistics",
        "university": "Cornell University",
        "comments":
            "Tier 2 Indian University. Applied on January 5th, interviewed on January 27. \
            Rejected on May 26. If you’re waiting till June, it’s rejection, good \
            luck.",
        "date_added": "May 26, 2026",
        "url": "https://www.thegradcafe.com/result/1020272",
        "status": "Rejected",
        "status_date": "May 26",
        "accepted": "None",
        "rejected": "May 26",
        "term": "Fall 2026",
        "US/International": "International",
        "degree": "Masters",
        "gpa": "3.45",
        "gre": "170",
        "grev": "157",
        "greaw": "4.00",
        "llm-generated-program": "Applied Statistics",
        "llm-generated-university": "Cornell University",
    },
    {
        "id": 1020271,
        "program": "Computer Science",
        "university": "Washington State University",
        "comments":
            "First interviews and said he will hire for Sping 2026. Then ghosted. And then \
            rejected over email stating no bandwidth.",
        "date_added": "May 26, 2026",
        "url": "https://www.thegradcafe.com/result/1020271",
        "status": "Interview",
        "status_date": "May 22",
        "accepted": "None",
        "rejected": "None",
        "term": "Fall 2026",
        "US/International": "International",
        "degree": "PhD",
        "gpa": "3.80",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "Computer Science",
        "llm-generated-university": "Washington State University",
    },
    {
        "id": 1020270,
        "program": "Computer Science",
        "university": "Michigan State University",
        "comments":
            "Applied for PhD but offered Masters. Asked for Integrated masters, but they refused.",
        "date_added": "May 26, 2026",
        "url": "https://www.thegradcafe.com/result/1020270",
        "status": "Accepted",
        "status_date": "May 26",
        "accepted": "None",
        "rejected": "None",
        "term": "Fall 2026",
        "US/International": "International",
        "degree": "PhD",
        "gpa": "3.80",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "Computer Science",
        "llm-generated-university": "Michigan State University",
    },
    {
        "id": 1020269,
        "program": "Education",
        "university": "Wilfrid Laurier University",
        "comments": "None",
        "date_added": "May 26, 2026",
        "url": "https://www.thegradcafe.com/result/1020269",
        "status": "Accepted",
        "status_date": "May 22",
        "accepted": "None",
        "rejected": "None",
        "term": "Fall 2026",
        "US/International": "American",
        "degree": "Masters",
        "gpa": "None",
        "gre": "None",
        "grev": "None",
        "greaw": "None",
        "llm-generated-program": "Education",
        "llm-generated-university": "Wilfrid Laurier University",
    },
]
